import Head from 'next/head';
import ParallaxWallpaper from '../components/ParallaxWallpaper';
import NormalContent from '../components/NormalContent';

export default function Home() {
	return (
		<>
			<Head>
				<title>Parallax NextJS</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<ParallaxWallpaper />
				<NormalContent />
				<ParallaxWallpaper />
				<NormalContent />
				<ParallaxWallpaper />
				<NormalContent />
				<ParallaxWallpaper />
			</main>
		</>
	);
}
